# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

tasks:
  build: go build -o ./out/rosalind ./cmd/rosalind/
  run: go run ./cmd/rosalind/
  format: go fmt ./...
  lint: go vet ./...
  check:
    cmds:
      - task format
      - task lint
