# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

tasks:
  build:
    desc: Builds the CLI
    cmd: go build -o ./out/rosalind ./cmd/rosalind/

  # Use -- to pass arguments to the CLI
  # Example: task run -- --help
  run:
    desc: Runs the CLI
    cmd: go run ./cmd/rosalind/ {{.CLI_ARGS}}

  format:
    desc: Formats Go code
    cmd: go fmt ./...

  lint:
    desc: Lints Go code
    cmd: go vet ./...

  check:
    desc: Formats and lints Go code
    cmds:
      - task format
      - task lint
